### ISSUE TITLE
which hosting service should we use ?

### ISSUE THREAD

**Issue by bozavci** [SWE574-TeamUnity/RepoUnity#3]
I think all of us used AWS in SWE573. Should we use a different hosting service or stick with AWS ? Are there any suggestions ?

**Comment by onatbas** [comment]
DigitalOcean is pretty slick, I guess. Why not use that? AWS has caused some problems for some people (resulting in huge bills). I say let's not risk it.

**Comment by bozavci** [comment]
I also considered digitalocean for hosting at first but I experienced some problems with it.  They closed my network port due to unusual traffic 4 days into creating a new droplet. If you were to use digitalocean we should consider the cost of maintaining snapshots as well otherwise its would be big risk :)

**Comment by onatbas** [comment]
that's weird indeed. I trust your judgment on this issue, then :)

**Comment by NurErtem** [comment]
last semester aws was a requirement kind of.  i spent lots of time reading aws documentation. my vote is for aws.

**Comment by ozanyarci** [comment]
I only know aws from previous experience. If you are using digitalocean professionally, i am Okay with it. Otherwise, I prefer aws.

**Comment by onatbas** [comment]
AWS is decided, aparently. feel free to re-open if there's an issue.
