### ISSUE TITLE
selecting a name for the group

### ISSUE THREAD

**Issue by koray-bostanci** [SWE574-TeamUnity/RepoUnity#4]
@NurErtem suggested to use "**Unity**" as the team/group name.
Is there any other nominee for the name?

We can vote all the choices. Or if it's ok for everyone, we can continue with this name and close this issue.

**Comment by bozavci** [comment]
I like this name I'm ok with it.

**Comment by onatbas** [comment]
I'm OK with the group name. For the project, we might decide on something catchier later on.

**Comment by eylulakar** [comment]
I'm okay with this group name.

**Comment by atabn** [comment]
'Unity' is OK for me.

**Comment by onatbas** [comment]
5 OK and Nur is the one who suggested so I guess this issue is resolved.
