### ISSUE TITLE
Decide on git branching strategy

### ISSUE THREAD

**Issue by onatbas** [SWE574-TeamUnity/RepoUnity#5]
I think we should decide on a git branching strategy as well. 

I suggest Atlassian GitFlow, which is simply feature branching from develop.
https://de.atlassian.com/git/tutorials/comparing-workflows

Any other suggestions ?

**Comment by koray-bostanci** [comment]
I've check the document and found it very useful. Actually Atlassian's documents about Git are very helpful.

I want to share another popular blog post about GitFlow which also explains Feature Branching.

[a-successful-git-branching-model](http://nvie.com/posts/a-successful-git-branching-model/ )

In summary, I agree with using GitFlow.

**Comment by NurErtem** [comment]
i also read the documents, and to my experience also it is simply makes sense to post to develop and merge afterwards.

**Comment by NurErtem** [comment]
according to this atlasian strategy which we agreed upon, does it make sense to open the project under organization or under repository if we are to keep mobile plug in codes under seperate repos or not? please share your experience. i have no working experience on this one.

**Comment by onatbas** [comment]
> post to develop and merge afterwards

Could you elaborate this part a bit more? What do you mean by posting to develop? If you mean to push to develop, where do you propose we should merge develop to?

> does it make sense to open the project under organization or under repository

Later on, 'mobile', 'plugin', 'backend' (possibly front end aswell?) are supposedly gonna be different repositories. It might be good to have their own dedicated Projects seperate, a central one will be too crowded to see which is which. 

It might be good to have a central project to track user stories, though, with linked issues from different projects, but you cannot create an issue that's dangling (doesn't belong to any repository) and link separate issues to that (that's a GitHub limitation, Projects is pretty new, I presume they'll add something like that in near future). So while in theory this could work, it's not possible to create issues without creating them in a project first. You can only create notes, which are simply plain text.

If the group can think of a workaround around that limitation, please share.

**Comment by NurErtem** [comment]
so under https://github.com/orgs/SWE574-TeamUnity/projects/1, i created a test project under organization, it populates all the issues created under all related repos attached to the team. i guess we can utilize this one in the if there is a need of multiple repos and projects of each repo, as pointed out it might be useful user stories etc but then again issues should be created under related repo. there might be a specific reason for this for big projects maybe. i do not know. we will see. i did not have expereince so i asked

**Comment by bozavci** [comment]
This is confusing to me as well. It seems like creating new repos for mobile and plugin development would be the ideal scenario but maintaining 3 repos with 8 developers will be challenging. Also we have to duplicates labels, boards and other github configurations as well. This is very difficult decision and I have no idea which one to choose :)

**Comment by onatbas** [comment]
Again, there's no support for user stories on github. 
We can decide on whether or not to use a central repository, on which my vote is not to do so. It will be crowded. I will adhere to the decision of the group.

**Comment by onatbas** [comment]
Everybody seems to be OK with GitFlow, we may open another case for repository discussion. For now, I'm closing branching issue. Please re-open if needs arise.
