### ISSUE TITLE
which technology stack on mobile should we choose?

### ISSUE THREAD

**Issue by onatbas** [SWE574-TeamUnity/RepoUnity#6]
I think it would be better to see everybody's experience and opinion. 

I have experience on mobile with Qt/C++ which I presume is gonna be immediately ruled out because no one likes C++ :) But Qt has nice networking capabilities and UI design tools.

At the opposite of spectrum I've used Flash/Adobe AIR for game development on mobile, If we're targeting a quite responsive app, I can be a guide on that as well. 

What about native mobile? Someone recommended PhoneGap, I guess. We can also give a shot to nativeScript as many of us are familiar with JS.

**Comment by bozavci** [comment]
Instructor specified she was expecting an android application for mobile app and I think we can have a hard time dealing with native aspects in the future if we choose to use responsive web app. 

I think we should either use native Android or one of the hybrid platforms. I would recommend Ionic for hybrid. I use it regularly and familiar with it. NativeScript is ok as well but ionic has a better community at this point.

**Comment by onatbas** [comment]
Yes, on the same page. I like Ionic as well! I have some colleagues working with it and they're quite happy with it.

**Comment by bozavci** [comment]
Lets vote on Ionic. If there are any objections please specify

**Comment by NurErtem** [comment]
i have no idea so i trust the judgement of the SMEs

**Comment by bozavci** [comment]
Closing the issue as Ionic. If anyone objects please re-open.
